# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0002_auto_20170128_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joueur',
            old_name='user_id',
            new_name='user',
        ),
    ]
