# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc', '0003_auto_20170128_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='trackmania_id',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
